apiVersion: v1
kind: Service
metadata:
  name: ytclone-service
  namespace: yt-clone
  labels:
    app: ytclone
spec:
  selector:
    app: ytclone
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
