name: YTCLONE App Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and Push Docker image with Layer Caching
        uses: docker/build-push-action@v5
        with:
          context: app/youtube-clone
          push: true
          tags: melvincv/ytclone:${{ github.ref_name }}-${{ github.run_number }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max

  replace-k8s-manifests:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Replace image in deployment manifest
        run: |
          export IMAGETAG="melvincv/ytclone:${{ github.ref_name }}-${{ github.run_number }}"
          sed -i "s|image:.*|image: ${IMAGETAG}|" kubernetes-manifests/yt-clone-app/2_deployment.yml

      - name: Replace Host in Ingress
        run: |
          export INGRESS_HOST=${{ vars.YTCLONE_INGRESS_HOST }}
          sed -i "s/host:.*/host: ${INGRESS_HOST}/" kubernetes-manifests/yt-clone-app/4_ingress.yml

      - name: Commit changes to repo
        uses: EndBug/add-and-commit@v9
        with:
          add: 'kubernetes-manifests/yt-clone-app'
          author_name: ${{ vars.CI_NAME }}
          author_email: ${{ vars.CI_EMAIL }}
          message: 'CI COMMIT: modify YTCLONE APP k8s manifests for RUN ${{ github.run_number }}'